// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.Joystick;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.MecanumDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;


//Import Import classes to use SparkMax motors
import com.revrobotics.spark.SparkMax;
import com.revrobotics.spark.config.SparkBaseConfig.IdleMode;
import com.revrobotics.spark.config.SparkMaxConfig;
import com.revrobotics.spark.SparkLowLevel.MotorType;

//Import classes top configure SparkMax motors
import com.revrobotics.spark.SparkBase.ControlType;
import com.revrobotics.spark.SparkBase.PersistMode;
import com.revrobotics.spark.SparkBase.ResetMode;
import frc.robot.Configs;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private final SparkMax driveFrontLeft;
private final SparkMax driveBackLeft;
private final SparkMax driveFrontRight;
private final SparkMax driveBackRight;
private MecanumDrive mecanumDrive1;



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//create motors
driveFrontLeft = new SparkMax(4, MotorType.kBrushless);
 //addChild("driveFrontLeft",driveFrontLeft);
 driveFrontLeft.setInverted(true);

driveBackLeft = new SparkMax(3, MotorType.kBrushless);
 //addChild("driveBackLeft",driveBackLeft);
 driveBackLeft.setInverted(true);

driveFrontRight = new SparkMax(1, MotorType.kBrushless);
 //addChild("driveFrontRight",driveFrontRight);
 driveFrontRight.setInverted(false);

driveBackRight = new SparkMax(2, MotorType.kBrushless);
 //addChild("driveBackRight",driveBackRight);
 driveBackRight.setInverted(false);

 //Configure the motors to have a brake mode and a current limit of 50 amps. This is important for safety and performance.
driveFrontLeft.configure(new SparkMaxConfig().idleMode(IdleMode.kBrake).smartCurrentLimit(50), ResetMode.kResetSafeParameters,
        PersistMode.kPersistParameters);

driveBackLeft.configure(new SparkMaxConfig().idleMode(IdleMode.kBrake).smartCurrentLimit(50), ResetMode.kResetSafeParameters,
        PersistMode.kPersistParameters);

driveFrontRight.configure(new SparkMaxConfig().idleMode(IdleMode.kBrake).smartCurrentLimit(50), ResetMode.kResetSafeParameters,
        PersistMode.kPersistParameters);

driveBackRight.configure(new SparkMaxConfig().idleMode(IdleMode.kBrake).smartCurrentLimit(50), ResetMode.kResetSafeParameters,
        PersistMode.kPersistParameters);

mecanumDrive1 = new MecanumDrive(driveFrontLeft, driveBackLeft,
driveFrontRight, driveBackRight);
 addChild("Mecanum Drive 1",mecanumDrive1);
 mecanumDrive1.setSafetyEnabled(true);
mecanumDrive1.setExpiration(0.1);
mecanumDrive1.setMaxOutput(1.0);



        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }
   
    public void drive(double x, double y, double theta){
        mecanumDrive1.driveCartesian(x, y, theta);
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

